package com.ytaoer.mybatis.client;

import com.ytaoer.mybatis.vo.Article;
import com.ytaoer.mybatis.vo.ArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int countByExample(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int deleteByExample(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int insert(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int insertSelective(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	List<Article> selectByExample(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	Article selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int updateByExampleSelective(@Param("record") Article record,
			@Param("example") ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int updateByExample(@Param("record") Article record,
			@Param("example") ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int updateByPrimaryKeySelective(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int updateByPrimaryKey(Article record);
}