package com.ytaoer.mybatis.client;

import com.ytaoer.mybatis.vo.ArticleText;
import com.ytaoer.mybatis.vo.ArticleTextExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleTextMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table articletext
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int countByExample(ArticleTextExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table articletext
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int deleteByExample(ArticleTextExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table articletext
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int insert(ArticleText record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table articletext
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int insertSelective(ArticleText record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table articletext
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	List<ArticleText> selectByExampleWithBLOBs(ArticleTextExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table articletext
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	List<ArticleText> selectByExample(ArticleTextExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table articletext
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int updateByExampleSelective(@Param("record") ArticleText record,
			@Param("example") ArticleTextExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table articletext
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") ArticleText record,
			@Param("example") ArticleTextExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table articletext
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int updateByExample(@Param("record") ArticleText record,
			@Param("example") ArticleTextExample example);
}