package com.ytaoer.mybatis.client;

import com.ytaoer.mybatis.vo.TagArticle;
import com.ytaoer.mybatis.vo.TagArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagArticleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag_article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int countByExample(TagArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag_article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int deleteByExample(TagArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag_article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag_article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int insert(TagArticle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag_article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int insertSelective(TagArticle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag_article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	List<TagArticle> selectByExample(TagArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag_article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	TagArticle selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag_article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int updateByExampleSelective(@Param("record") TagArticle record,
			@Param("example") TagArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag_article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int updateByExample(@Param("record") TagArticle record,
			@Param("example") TagArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag_article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int updateByPrimaryKeySelective(TagArticle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag_article
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int updateByPrimaryKey(TagArticle record);
}