package com.ytaoer.mybatis.client;

import com.ytaoer.mybatis.vo.Tag;
import com.ytaoer.mybatis.vo.TagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int countByExample(TagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int deleteByExample(TagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int insert(Tag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int insertSelective(Tag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	List<Tag> selectByExample(TagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	Tag selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int updateByExampleSelective(@Param("record") Tag record,
			@Param("example") TagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int updateByExample(@Param("record") Tag record,
			@Param("example") TagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int updateByPrimaryKeySelective(Tag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tag
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	int updateByPrimaryKey(Tag record);
}