package com.ytaoer.mybatis.vo;

import java.util.Date;

public class Article {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.id
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.title
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.bref
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	private String bref;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.viewnum
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	private Integer viewnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.author
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.createdate
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.pic
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	private String pic;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.id
	 * @return  the value of article.id
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.id
	 * @param id  the value for article.id
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.title
	 * @return  the value of article.title
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.title
	 * @param title  the value for article.title
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.bref
	 * @return  the value of article.bref
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public String getBref() {
		return bref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.bref
	 * @param bref  the value for article.bref
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public void setBref(String bref) {
		this.bref = bref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.viewnum
	 * @return  the value of article.viewnum
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public Integer getViewnum() {
		return viewnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.viewnum
	 * @param viewnum  the value for article.viewnum
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public void setViewnum(Integer viewnum) {
		this.viewnum = viewnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.author
	 * @return  the value of article.author
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.author
	 * @param author  the value for article.author
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.createdate
	 * @return  the value of article.createdate
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.createdate
	 * @param createdate  the value for article.createdate
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.pic
	 * @return  the value of article.pic
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public String getPic() {
		return pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.pic
	 * @param pic  the value for article.pic
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public void setPic(String pic) {
		this.pic = pic;
	}
}