package com.ytaoer.mybatis.vo;

public class ArticleText {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column articletext.id
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column articletext.text
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	private String text;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column articletext.id
	 * @return  the value of articletext.id
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column articletext.id
	 * @param id  the value for articletext.id
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column articletext.text
	 * @return  the value of articletext.text
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public String getText() {
		return text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column articletext.text
	 * @param text  the value for articletext.text
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public void setText(String text) {
		this.text = text;
	}
}