package com.ytaoer.mybatis.vo;

public class CategoryArticle {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category_article.id
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category_article.categoryId
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	private Integer categoryid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category_article.articleId
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	private Integer articleid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category_article.id
	 * @return  the value of category_article.id
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category_article.id
	 * @param id  the value for category_article.id
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category_article.categoryId
	 * @return  the value of category_article.categoryId
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public Integer getCategoryid() {
		return categoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category_article.categoryId
	 * @param categoryid  the value for category_article.categoryId
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public void setCategoryid(Integer categoryid) {
		this.categoryid = categoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category_article.articleId
	 * @return  the value of category_article.articleId
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public Integer getArticleid() {
		return articleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category_article.articleId
	 * @param articleid  the value for category_article.articleId
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public void setArticleid(Integer articleid) {
		this.articleid = articleid;
	}
}