package com.ytaoer.mybatis.vo;

public class Tag {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tag.id
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tag.name
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tag.num
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	private Integer num;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tag.id
	 * @return  the value of tag.id
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tag.id
	 * @param id  the value for tag.id
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tag.name
	 * @return  the value of tag.name
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tag.name
	 * @param name  the value for tag.name
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tag.num
	 * @return  the value of tag.num
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tag.num
	 * @param num  the value for tag.num
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public void setNum(Integer num) {
		this.num = num;
	}
}