package com.ytaoer.mybatis.vo;

public class TagArticle {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tag_article.id
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tag_article.tagId
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	private Integer tagid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tag_article.articleId
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	private Integer articleid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tag_article.id
	 * @return  the value of tag_article.id
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tag_article.id
	 * @param id  the value for tag_article.id
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tag_article.tagId
	 * @return  the value of tag_article.tagId
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public Integer getTagid() {
		return tagid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tag_article.tagId
	 * @param tagid  the value for tag_article.tagId
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public void setTagid(Integer tagid) {
		this.tagid = tagid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tag_article.articleId
	 * @return  the value of tag_article.articleId
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public Integer getArticleid() {
		return articleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tag_article.articleId
	 * @param articleid  the value for tag_article.articleId
	 * @mbggenerated  Thu Oct 27 12:37:35 GMT+08:00 2016
	 */
	public void setArticleid(Integer articleid) {
		this.articleid = articleid;
	}
}